extends "res://ui/tests/test_school_fifth_planning_window.gd"


func _preparation_bounds(panel) -> void:
	for index in range(3):
		await process_frame
	var screen := Rect2(Vector2.ZERO,Vector2(root.size))
	for control in [panel._adventure,panel.adventure_round_label,panel.adventure_status,
			panel.adventure_start_button,panel.next_button,panel._guidance,panel.footer]:
		_check(screen.encloses(control.get_global_rect()),"departure control fits viewport")
	for button in panel.adventure_member_buttons.values():
		_check(panel._adventure.get_global_rect().encloses(button.get_global_rect()),"current squad card fits panel")
	_check(panel.adventure_start_button.disabled,"actual mandatory battle stays unavailable")


func _run() -> void:
	_cleanup()
	root.size = Vector2i(1024,768)
	root.gui_embed_subwindows = true
	if root.has_meta("school_playground_save_path"):
		root.remove_meta("school_playground_save_path")
	var fixture: Dictionary = Roles._integers(JSON.parse_string(FileAccess.get_file_as_string("res://data/school_playground_legacy_v3.json")))
	var file := FileAccess.open(TEST_PATH,FileAccess.WRITE)
	file.store_string(JSON.stringify(fixture["cases"][1]["save"]));file.close()
	var panel = await _new_panel()
	await _click(panel.arrival.continue_button)
	await _click(panel.workroom.continue_button)
	await _click(panel.story_reader.skip_button)
	await _dialog_click(panel.story_reader.skip_dialog.get_ok_button())
	_check(panel.model.stage() == "fifth_planning","actual workroom UI enters fifth school")
	var state: Dictionary = panel.model.state()
	var disk := FileAccess.get_sha256(TEST_PATH)
	await _click(panel.next_button)
	_check(panel.page == "adventure" and panel._adventure.visible,"mandatory button opens squad preparation")
	_check(panel.adventure_projection["ready"] and panel.adventure_member_buttons.size() == 4,"initial squad shows current teacher and three students")
	for pair in [[3,"HP 117  ·  MP 445"],[4,"HP 75  ·  MP 69"],[9,"HP 57  ·  MP 87"]]:
		_check(panel.adventure_member_buttons[pair[0]].text.contains(pair[1]),"current grown student shows source HP/MP")
	_check(not panel.adventure_member_buttons[101].text.contains("HP"),"teacher leader is not assigned student combat limits")
	# Declared fault injection, restored before subsequent saved-state checks.
	var entry_before: Dictionary = panel.model._school_entry.duplicate(true)
	panel.model._school_entry["after"]["participants"][0]["equipped_items"][0] = 1
	var refused_state: Dictionary = panel.model.state()
	panel.refresh()
	_check(not panel.adventure_limits["supported"],"unsupported loadout refuses entire limits projection")
	for student in [3,4,9]:
		_check(panel.adventure_member_buttons[student].text.contains("战斗数值暂不可用"),"unsupported limits show no demo fallback")
	_check(panel.model.state() == refused_state and panel.adventure_start_button.disabled,"unavailable limits preserve state and disabled battle")
	await _preparation_bounds(panel)
	await _capture("departure_limits_unavailable")
	panel.model._school_entry = entry_before
	panel.refresh()
	_check(panel.adventure_round_label.text.contains("任务5") and panel.adventure_round_label.text.contains("场景5"),"source adventure and scene shown")
	_check(panel.model.state() == state and FileAccess.get_sha256(TEST_PATH) == disk,"opening projection changes neither school nor save")
	await _preparation_bounds(panel)
	await _capture("departure_initial")
	await _click(panel.adventure_member_buttons[4])
	_check(panel.detail_id == 4 and panel.model.state() == state,"squad portrait inspects current grown student")
	await _capture("departure_member_detail")
	await _click(panel.adventure_start_button)
	_check(panel.page == "adventure" and panel.model.state() == state,"disabled start grants no battle or reward")
	await _click(panel.next_button)
	_check(panel.page == "groups","return button opens editable fifth school")
	await _click(panel.student_buttons[0][2]);await _click(panel.wait_target)
	state = panel.model.state();disk = FileAccess.get_sha256(TEST_PATH)
	await _click(panel.next_button)
	_check(panel.adventure_projection["prepared"]["rounds"][0]["student_ids"] == [3,4],"waiting student removed from source squad")
	_check(panel.adventure_projection["idle_student_ids"] == [9],"waiting identity preserved separately")
	_check(panel.adventure_limits["students"].size() == 2 and panel.adventure_member_buttons[3].text.contains("HP 117"),"waiting edit recomputes current limits")
	_check(panel.adventure_member_buttons.size() == 3 and not panel.adventure_member_buttons.has(9),"waiting member does not appear as participant")
	_check(panel.model.state() == state and FileAccess.get_sha256(TEST_PATH) == disk,"repeated preparation never persists new commands")
	await _preparation_bounds(panel)
	await _capture("departure_waiting")
	await _click(panel.next_button)
	await _click(panel.teacher_buttons[0]);await _click(panel.teacher_buttons[4])
	state = panel.model.state()
	await _click(panel.next_button)
	_check(not panel.adventure_projection["ready"] and panel.adventure_status.text.contains("5班尚无学生"),"teacher-only fifth class explains refusal")
	_check(panel.adventure_member_buttons.is_empty() and panel.model.state() == state,"unready plan has no fake prepared squad")
	await _preparation_bounds(panel)
	await _capture("departure_teacher_only")
	await _click(panel.next_button)
	await _click(panel.waiting_buttons[3]);await _click(panel.student_buttons[4][0])
	await _click(panel.waiting_buttons[4]);await _click(panel.student_buttons[4][1])
	state = panel.model.state()
	await _click(panel.next_button)
	var round: Dictionary = panel.adventure_projection["prepared"]["rounds"][0]
	_check(round["teacher_ids"] == [101] and round["student_ids"] == [3,4] and round["student_groups"] == [4,4],"edited current fifth class feeds native-equivalent round")
	_check(panel.adventure_member_buttons[4].text.contains("5班"),"card displays actual updated class")
	_check(panel.adventure_member_buttons[4].text.contains("HP 75  ·  MP 69"),"class change retains current role limits")
	await _preparation_bounds(panel)
	await _capture("departure_fifth_class")
	await _click(panel.save_button)
	var payload: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(TEST_PATH))
	_check(payload["version"] == 4 and payload["rules"].size() == 10,"saving preparation preserves existing v4 format")
	_check(panel.model.state() == state,"saving projection preserves earned school state")
	await _capture("departure_saved")
	root.remove_child(panel);panel.queue_free()
	panel = await _new_panel()
	_check(panel.page == "groups" and panel.model.state() == state,"fresh launch restores fifth class rather than invented battle state")
	await _click(panel.next_button)
	_check(panel.adventure_projection["prepared"]["rounds"][0] == round,"reopening derives identical saved squad")
	_check(panel.adventure_member_buttons[3].text.contains("HP 117  ·  MP 445"),"fresh save restore retains earned combat limits")
	await _preparation_bounds(panel)
	await _capture("departure_restored")
	disk = FileAccess.get_sha256(TEST_PATH)
	panel.save_path = "user://missing_departure_preparation_directory/state.json"
	await _click(panel.save_button)
	_check(panel.page == "adventure" and panel.model.state() == state and panel._save_message.contains("失败"),"save failure preserves current preparation")
	panel.save_path = TEST_PATH
	_check(FileAccess.get_sha256(TEST_PATH) == disk,"failed save preserves existing v4 file")
	await _capture("departure_save_failure")
	await _click(panel.restart_button);await _dialog_click(panel.restart_dialog.get_cancel_button())
	_check(panel.page == "adventure" and panel.model.state() == state and FileAccess.get_sha256(TEST_PATH) == disk,"restart cancellation preserves preparation and disk")
	await _click(panel.tab_buttons["results"])
	_check(panel.mvp_label.text == "帕弥菈","fourth-week source MVP remains reviewable")
	await _click(panel.next_button);await _click(panel.next_button)
	_check(panel.page == "adventure" and panel.model.state() == state,"review round trip never repeats growth or reward")
	await _click(panel.workroom_button);await _click(panel.workroom.continue_button);await _click(panel.next_button)
	_check(panel.page == "adventure" and panel.model.state() == state,"workroom round trip retains current source squad")
	await _click(panel.tab_buttons["courses"])
	for button in panel.course_buttons.values():
		_check(button.disabled,"mandatory gate still blocks teaching")
	await _click(panel.next_button)
	_check(panel.page == "adventure" and panel.model.state() == state,"course view can return to current departure")
	await _click(panel.next_button)
	await _click(panel.teacher_buttons[4]);await _click(panel.wait_target)
	state = panel.model.state()
	await _click(panel.next_button)
	_check(not panel.adventure_projection["ready"] and panel.adventure_status.text.contains("至少一个"),"no active teacher prevents readiness")
	_check(panel.adventure_projection["idle_teacher_ids"] == [101] and panel.model.state() == state,"idle teacher remains outside squad without reward")
	await _preparation_bounds(panel)
	await _capture("departure_all_waiting")
	panel.queue_free();await process_frame
	if root.has_meta("school_playground_save_path"):
		root.remove_meta("school_playground_save_path")
	_cleanup()
	_finish()
